/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { CreateUserGroupRequestModelDocumentStartNode } from './createUserGroupRequestModelDocumentStartNode.js';
import type { CreateUserGroupRequestModelMediaStartNode } from './createUserGroupRequestModelMediaStartNode.js';
import type { CreateUserGroupRequestModelPermissionsItem } from './createUserGroupRequestModelPermissionsItem.js';

export interface CreateUserGroupRequestModel {
  name: string;
  alias: string;
  /** @nullable */
  icon?: string | null;
  sections: string[];
  languages: string[];
  hasAccessToAllLanguages: boolean;
  /** @nullable */
  documentStartNode?: CreateUserGroupRequestModelDocumentStartNode;
  documentRootAccess: boolean;
  /** @nullable */
  mediaStartNode?: CreateUserGroupRequestModelMediaStartNode;
  mediaRootAccess: boolean;
  fallbackPermissions: string[];
  permissions: CreateUserGroupRequestModelPermissionsItem[];
  /** @nullable */
  id?: string | null;
}
