/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { CreateMediaTypePropertyTypeRequestModel } from './createMediaTypePropertyTypeRequestModel.js';
import type { CreateMediaTypePropertyTypeContainerRequestModel } from './createMediaTypePropertyTypeContainerRequestModel.js';
import type { CreateMediaTypeRequestModelParent } from './createMediaTypeRequestModelParent.js';
import type { MediaTypeSortModel } from './mediaTypeSortModel.js';
import type { MediaTypeCompositionModel } from './mediaTypeCompositionModel.js';
import type { CreateMediaTypeRequestModelCollection } from './createMediaTypeRequestModelCollection.js';

export interface CreateMediaTypeRequestModel {
  /** @minLength 1 */
  alias: string;
  /** @minLength 1 */
  name: string;
  /** @nullable */
  description?: string | null;
  /** @minLength 1 */
  icon: string;
  allowedAsRoot: boolean;
  variesByCulture: boolean;
  variesBySegment: boolean;
  isElement: boolean;
  properties: CreateMediaTypePropertyTypeRequestModel[];
  containers: CreateMediaTypePropertyTypeContainerRequestModel[];
  /** @nullable */
  id?: string | null;
  /** @nullable */
  parent?: CreateMediaTypeRequestModelParent;
  allowedMediaTypes: MediaTypeSortModel[];
  compositions: MediaTypeCompositionModel[];
  /** @nullable */
  collection?: CreateMediaTypeRequestModelCollection;
}
