/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DataTypePropertyPresentationModel } from './dataTypePropertyPresentationModel.js';
import type { CreateDataTypeRequestModelParent } from './createDataTypeRequestModelParent.js';

export interface CreateDataTypeRequestModel {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  editorAlias: string;
  editorUiAlias: string;
  values: DataTypePropertyPresentationModel[];
  /** @nullable */
  id?: string | null;
  /** @nullable */
  parent?: CreateDataTypeRequestModelParent;
}
