/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentValueModel } from './documentValueModel.js';
import type { DocumentVariantRequestModel } from './documentVariantRequestModel.js';
import type { CreateDocumentBlueprintRequestModelParent } from './createDocumentBlueprintRequestModelParent.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';

export interface CreateDocumentBlueprintRequestModel {
  values: DocumentValueModel[];
  variants: DocumentVariantRequestModel[];
  /** @nullable */
  id?: string | null;
  /** @nullable */
  parent?: CreateDocumentBlueprintRequestModelParent;
  documentType: ReferenceByIdModel;
}
