/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DataTypeTreeItemResponseModelParent } from './dataTypeTreeItemResponseModelParent.js';

export interface DataTypeTreeItemResponseModel {
  hasChildren: boolean;
  id: string;
  /** @nullable */
  parent?: DataTypeTreeItemResponseModelParent;
  name: string;
  isFolder: boolean;
  /** @nullable */
  editorUiAlias?: string | null;
  isDeletable: boolean;
}
