/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentItemResponseModelParent } from './documentItemResponseModelParent.js';
import type { DocumentTypeReferenceResponseModel } from './documentTypeReferenceResponseModel.js';
import type { DocumentVariantItemResponseModel } from './documentVariantItemResponseModel.js';

export interface DocumentItemResponseModel {
  id: string;
  isTrashed: boolean;
  isProtected: boolean;
  /** @nullable */
  parent?: DocumentItemResponseModelParent;
  hasChildren: boolean;
  documentType: DocumentTypeReferenceResponseModel;
  variants: DocumentVariantItemResponseModel[];
}
