/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentValueResponseModel } from './documentValueResponseModel.js';
import type { DocumentVariantResponseModel } from './documentVariantResponseModel.js';
import type { DocumentTypeReferenceResponseModel } from './documentTypeReferenceResponseModel.js';
import type { DocumentVersionResponseModelDocument } from './documentVersionResponseModelDocument.js';

export interface DocumentVersionResponseModel {
  values: DocumentValueResponseModel[];
  variants: DocumentVariantResponseModel[];
  id: string;
  documentType: DocumentTypeReferenceResponseModel;
  /** @nullable */
  document?: DocumentVersionResponseModelDocument;
}
