/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentValueResponseModel } from './documentValueResponseModel.js';
import type { DocumentVariantResponseModel } from './documentVariantResponseModel.js';
import type { DocumentTypeCollectionReferenceResponseModel } from './documentTypeCollectionReferenceResponseModel.js';

export interface DocumentCollectionResponseModel {
  values: DocumentValueResponseModel[];
  variants: DocumentVariantResponseModel[];
  id: string;
  /** @nullable */
  creator?: string | null;
  sortOrder: number;
  documentType: DocumentTypeCollectionReferenceResponseModel;
  isTrashed: boolean;
  isProtected: boolean;
  /** @nullable */
  updater?: string | null;
}
