/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { UserOrderModel } from './userOrderModel.js';
import type { DirectionModel } from './directionModel.js';
import type { UserStateModel } from './userStateModel.js';

export type GetFilterUserParams = {
skip?: number;
take?: number;
orderBy?: UserOrderModel;
orderDirection?: DirectionModel;
userGroupIds?: string[];
userStates?: UserStateModel[];
filter?: string;
};
