/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberValueResponseModel } from './memberValueResponseModel.js';
import type { MemberVariantResponseModel } from './memberVariantResponseModel.js';
import type { MemberTypeReferenceResponseModel } from './memberTypeReferenceResponseModel.js';
import type { MemberKindModel } from './memberKindModel.js';

export interface MemberResponseModel {
  values: MemberValueResponseModel[];
  variants: MemberVariantResponseModel[];
  id: string;
  email: string;
  username: string;
  memberType: MemberTypeReferenceResponseModel;
  isApproved: boolean;
  isLockedOut: boolean;
  isTwoFactorEnabled: boolean;
  failedPasswordAttempts: number;
  /** @nullable */
  lastLoginDate?: string | null;
  /** @nullable */
  lastLockoutDate?: string | null;
  /** @nullable */
  lastPasswordChangeDate?: string | null;
  groups: string[];
  kind: MemberKindModel;
}
