/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { RelationTypeResponseModelParentObject } from './relationTypeResponseModelParentObject.js';
import type { RelationTypeResponseModelChildObject } from './relationTypeResponseModelChildObject.js';

export interface RelationTypeResponseModel {
  /** @minLength 1 */
  name: string;
  isBidirectional: boolean;
  isDependency: boolean;
  id: string;
  /** @nullable */
  alias?: string | null;
  /** @nullable */
  parentObject?: RelationTypeResponseModelParentObject;
  /** @nullable */
  childObject?: RelationTypeResponseModelChildObject;
}
