/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export type RuntimeModeModel = typeof RuntimeModeModel[keyof typeof RuntimeModeModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RuntimeModeModel = {
  BackofficeDevelopment: 'BackofficeDevelopment',
  Development: 'Development',
  Production: 'Production',
} as const;
