/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { TemplateResponseModelMasterTemplate } from './templateResponseModelMasterTemplate.js';

export interface TemplateResponseModel {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  alias: string;
  /** @nullable */
  content?: string | null;
  id: string;
  /** @nullable */
  masterTemplate?: TemplateResponseModelMasterTemplate;
}
