/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberValueModel } from './memberValueModel.js';
import type { MemberVariantRequestModel } from './memberVariantRequestModel.js';

export interface UpdateMemberRequestModel {
  values: MemberValueModel[];
  variants: MemberVariantRequestModel[];
  email: string;
  username: string;
  /** @nullable */
  oldPassword?: string | null;
  /** @nullable */
  newPassword?: string | null;
  /** @nullable */
  groups?: string[] | null;
  isApproved: boolean;
  isLockedOut: boolean;
  isTwoFactorEnabled: boolean;
}
