/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { UpdateWebhookRequestModelHeaders } from './updateWebhookRequestModelHeaders.js';

export interface UpdateWebhookRequestModel {
  enabled: boolean;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  /** @minLength 1 */
  url: string;
  contentTypeKeys: string[];
  headers: UpdateWebhookRequestModelHeaders;
  events: string[];
}
