/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DictionaryItemTranslationModel } from './dictionaryItemTranslationModel.js';

export interface UpdateDictionaryItemRequestModel {
  /** @minLength 1 */
  name: string;
  translations: DictionaryItemTranslationModel[];
}
