/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { UpdateMediaTypePropertyTypeContainerRequestModelParent } from './updateMediaTypePropertyTypeContainerRequestModelParent.js';

export interface UpdateMediaTypePropertyTypeContainerRequestModel {
  id: string;
  /** @nullable */
  parent?: UpdateMediaTypePropertyTypeContainerRequestModelParent;
  /** @nullable */
  name?: string | null;
  /** @minLength 1 */
  type: string;
  sortOrder: number;
}
