/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export interface UpgradeSettingsResponseModel {
  /** @minLength 1 */
  currentState: string;
  /** @minLength 1 */
  newState: string;
  /** @minLength 1 */
  newVersion: string;
  /** @minLength 1 */
  oldVersion: string;
  readonly reportUrl: string;
}
