/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export type UserOrderModel = typeof UserOrderModel[keyof typeof UserOrderModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserOrderModel = {
  UserName: 'UserName',
  Language: 'Language',
  Name: 'Name',
  Email: 'Email',
  Id: 'Id',
  CreateDate: 'CreateDate',
  UpdateDate: 'UpdateDate',
  IsApproved: 'IsApproved',
  IsLockedOut: 'IsLockedOut',
  LastLoginDate: 'LastLoginDate',
} as const;
