/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export type UserDataOperationStatusModel = typeof UserDataOperationStatusModel[keyof typeof UserDataOperationStatusModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserDataOperationStatusModel = {
  Success: 'Success',
  NotFound: 'NotFound',
  UserNotFound: 'UserNotFound',
  AlreadyExists: 'AlreadyExists',
} as const;
