/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export interface WebhookLogResponseModel {
  key: string;
  webhookKey: string;
  statusCode: string;
  isSuccessStatusCode: boolean;
  date: string;
  eventAlias: string;
  url: string;
  retryCount: number;
  requestHeaders: string;
  requestBody: string;
  responseHeaders: string;
  responseBody: string;
  exceptionOccured: boolean;
}
