/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MediaValueModel } from './mediaValueModel.js';
import type { MediaVariantRequestModel } from './mediaVariantRequestModel.js';
import type { CreateMediaRequestModelParent } from './createMediaRequestModelParent.js';
import type { ReferenceByIdModel } from './referenceByIdModel.js';

export interface CreateMediaRequestModel {
  values: MediaValueModel[];
  variants: MediaVariantRequestModel[];
  /** @nullable */
  id?: string | null;
  /** @nullable */
  parent?: CreateMediaRequestModelParent;
  mediaType: ReferenceByIdModel;
}
