/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DirectionModel } from './directionModel.js';

export type GetFilterMemberParams = {
memberTypeId?: string;
memberGroupName?: string;
isApproved?: boolean;
isLockedOut?: boolean;
orderBy?: string;
orderDirection?: DirectionModel;
filter?: string;
skip?: number;
take?: number;
};
