/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberTypeReferenceResponseModel } from './memberTypeReferenceResponseModel.js';
import type { VariantItemResponseModel } from './variantItemResponseModel.js';
import type { MemberKindModel } from './memberKindModel.js';

export interface MemberItemResponseModel {
  id: string;
  memberType: MemberTypeReferenceResponseModel;
  variants: VariantItemResponseModel[];
  kind: MemberKindModel;
}
