/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export interface ActionWorkflowRequestModel {
  comment: string;
  instanceGuid: string;
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  assignTo?: string | null;
}
