/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { WorkflowTaskModel } from './workflowTaskModel.js';

/**
 * @nullable
 */
export type ActiveTasksModelInvariantTask = WorkflowTaskModel | null;
