/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { SelectableContentTypePropertyDetailModel } from './selectableContentTypePropertyDetailModel.js';
import type { SelectableNameKeyPairModel } from './selectableNameKeyPairModel.js';

export interface AdvancedSearchScaffoldResponseModel {
  contentTypes: SelectableContentTypePropertyDetailModel[];
  dataTypes: SelectableNameKeyPairModel[];
  propertyEditors: SelectableNameKeyPairModel[];
}
