/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export interface AdvancedSearchResponseItemModel {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  documentTypeAlias?: string | null;
  /** @nullable */
  id?: number | null;
  key: string;
  published: boolean;
  score: number;
  icon: string;
  /** @nullable */
  culture?: string[] | null;
}
