/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { AdvancedSearchQueryModelFields } from './advancedSearchQueryModelFields.js';
import type { AdvancedSearchQueryModelBaseFields } from './advancedSearchQueryModelBaseFields.js';
import type { AdvancedSearchTypeModel } from './advancedSearchTypeModel.js';

export interface AdvancedSearchQueryModel {
  /** @nullable */
  contentTypes?: string[] | null;
  /** @nullable */
  cultures?: string[] | null;
  fields: AdvancedSearchQueryModelFields;
  baseFields: AdvancedSearchQueryModelBaseFields;
  category: string;
  searchType: AdvancedSearchTypeModel;
  take: number;
  skip: number;
  fuzzy: boolean;
}
