/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type AlternateVersionStatusModel = typeof AlternateVersionStatusModel[keyof typeof AlternateVersionStatusModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlternateVersionStatusModel = {
  Draft: 'Draft',
  ReadyToPublish: 'ReadyToPublish',
  Published: 'Published',
  PendingApproval: 'PendingApproval',
} as const;
