/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { AlternateVersionStatusModel } from './alternateVersionStatusModel.js';

export interface AlternateVersionCollectionResponseModel {
  unique: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  updateDate?: string | null;
  /** @nullable */
  icon?: string | null;
  /** @nullable */
  active?: boolean | null;
  /** @nullable */
  variant?: string | null;
  /** @nullable */
  segment?: string | null;
  status: AlternateVersionStatusModel;
  inSet: string[];
}
