/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { PropertyValueDtoModel } from './propertyValueDtoModel.js';
import type { AlternateVersionStatusModel } from './alternateVersionStatusModel.js';
import type { ReleaseSetCollectionResponseModel } from './releaseSetCollectionResponseModel.js';

export interface AlternateVersionDetailResponseModel {
  readonly entityType: string;
  icon: string;
  unique: string;
  parentUnique: string;
  /** @nullable */
  versionName?: string | null;
  /** @nullable */
  variant?: string | null;
  /** @nullable */
  segment?: string | null;
  /** @nullable */
  createDate?: string | null;
  /** @nullable */
  updateDate?: string | null;
  values: PropertyValueDtoModel[];
  /** @nullable */
  active?: boolean | null;
  status: AlternateVersionStatusModel;
  sets: ReleaseSetCollectionResponseModel[];
  /** @nullable */
  documentName?: string | null;
}
