/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ApprovalThresholdModel } from './approvalThresholdModel.js';

export interface ApprovalGroupDetailPermissionConfigModel {
  permission: number;
  /** @nullable */
  name?: string | null;
  approvalThreshold: ApprovalThresholdModel;
  /** @nullable */
  icon?: string | null;
  groupUnique: string;
}
