/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export interface ApprovalGroupCollectionMemberResponseModel {
  /** @nullable */
  name?: string | null;
  inherited: boolean;
  /** @nullable */
  email?: string | null;
}
