/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export interface ApprovalGroupDetailPermissionResponseModel {
  /** @nullable */
  unique?: string | null;
  permission: number;
  /** @nullable */
  culture?: string | null;
  /** @nullable */
  icon?: string | null;
  /** @nullable */
  name?: string | null;
  documentPermission: boolean;
  newDocumentPermission: boolean;
  groupUnique: string;
}
