/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type ApprovalThresholdModel = typeof ApprovalThresholdModel[keyof typeof ApprovalThresholdModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApprovalThresholdModel = {
  One: 'One',
  Most: 'Most',
  All: 'All',
} as const;
