/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type AuditTypeModel = typeof AuditTypeModel[keyof typeof AuditTypeModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuditTypeModel = {
  New: 'New',
  Save: 'Save',
  SaveVariant: 'SaveVariant',
  Open: 'Open',
  Delete: 'Delete',
  Publish: 'Publish',
  PublishVariant: 'PublishVariant',
  SendToPublish: 'SendToPublish',
  SendToPublishVariant: 'SendToPublishVariant',
  Unpublish: 'Unpublish',
  UnpublishVariant: 'UnpublishVariant',
  Move: 'Move',
  Copy: 'Copy',
  AssignDomain: 'AssignDomain',
  PublicAccess: 'PublicAccess',
  Sort: 'Sort',
  Notify: 'Notify',
  System: 'System',
  RollBack: 'RollBack',
  PackagerInstall: 'PackagerInstall',
  PackagerUninstall: 'PackagerUninstall',
  Custom: 'Custom',
  ContentVersionPreventCleanup: 'ContentVersionPreventCleanup',
  ContentVersionEnableCleanup: 'ContentVersionEnableCleanup',
} as const;
