/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { AuditTypeModel } from './auditTypeModel.js';

export interface AuditLogResponseModel {
  user: ReferenceByIdModel;
  timestamp: string;
  logType: AuditTypeModel;
  /** @nullable */
  comment?: string | null;
  /** @nullable */
  parameters?: string | null;
}
