/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ChartSeriesModel } from './chartSeriesModel.js';
import type { ChartResponseModelAdditionalData } from './chartResponseModelAdditionalData.js';

export interface ChartResponseModel {
  series: ChartSeriesModel[];
  additionalData: ChartResponseModelAdditionalData;
  currentUserLocale: string;
}
