/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export interface ContentSlimModel {
  /** @nullable */
  path?: string | null;
  /** @nullable */
  nodeName?: string | null;
  nodeId: number;
  contentTypeId: number;
  /** @nullable */
  contentTypeAlias?: string | null;
  icon: string;
  trashed: boolean;
  key: string;
  contentTypeKey: string;
}
