/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type ContentVariationModel = typeof ContentVariationModel[keyof typeof ContentVariationModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentVariationModel = {
  Nothing: 'Nothing',
  Culture: 'Culture',
  Segment: 'Segment',
  CultureAndSegment: 'CultureAndSegment',
} as const;
