/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ContentReviewsDetailedConfigModel } from './contentReviewsDetailedConfigModel.js';
import type { ContentReviewsSettingsModel } from './contentReviewsSettingsModel.js';

export interface ContentReviewsSaveSettingsModel {
  config: ContentReviewsDetailedConfigModel[];
  settings: ContentReviewsSettingsModel;
  delete: number[];
  regenerate: boolean;
}
