/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ApprovalGroupItemResponseModel } from './approvalGroupItemResponseModel.js';
import type { ContentReviewCollectionResponseModelDocument } from './contentReviewCollectionResponseModelDocument.js';

export interface ContentReviewCollectionResponseModel {
  /** @nullable */
  dueOn?: string | null;
  /** @nullable */
  lastReviewed?: string | null;
  reviewPeriod: number;
  groups: ApprovalGroupItemResponseModel[];
  /** @nullable */
  document?: ContentReviewCollectionResponseModelDocument;
}
