/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { PropertyModel } from './propertyModel.js';

export interface ContentTypePropertyModel {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  alias?: string | null;
  id: number;
  key: string;
  varies: boolean;
  icon: string;
  properties: PropertyModel[];
}
