/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type DirectionModel = typeof DirectionModel[keyof typeof DirectionModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DirectionModel = {
  Ascending: 'Ascending',
  Descending: 'Descending',
} as const;
