/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ApprovalGroupDetailPermissionConfigModel } from './approvalGroupDetailPermissionConfigModel.js';

export interface DocumentConfigUpdateRequestModel {
  /** @nullable */
  key?: string | null;
  /** @nullable */
  variant?: string | null;
  permissions: ApprovalGroupDetailPermissionConfigModel[];
}
