/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { DocumentTypePermissionConfigModel } from './documentTypePermissionConfigModel.js';

export interface DocumentTypeConfigResponseModel {
  /** @nullable */
  key?: string | null;
  permissions: DocumentTypePermissionConfigModel[];
}
