/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export interface DocumentItemResponseModel {
  /** @nullable */
  name?: string | null;
  unique: string;
  /** @nullable */
  icon?: string | null;
  culture: string;
}
