/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type EmailTypeModel = typeof EmailTypeModel[keyof typeof EmailTypeModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EmailTypeModel = {
  ApprovalRequest: 'ApprovalRequest',
  ApprovalRejection: 'ApprovalRejection',
  ApprovedAndCompleted: 'ApprovedAndCompleted',
  ApprovedAndCompletedForScheduler: 'ApprovedAndCompletedForScheduler',
  WorkflowCancelled: 'WorkflowCancelled',
  WorkflowErrored: 'WorkflowErrored',
  Reminder: 'Reminder',
  ContentReview: 'ContentReview',
} as const;
