/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type FlowTypeModel = typeof FlowTypeModel[keyof typeof FlowTypeModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FlowTypeModel = {
  Explicit: 'Explicit',
  Implicit: 'Implicit',
  Exclude: 'Exclude',
} as const;
