/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type GetApprovalGroupParams = {
skip?: number;
take?: number;
filter?: string;
};
