/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { EmailTypeModel } from './emailTypeModel.js';

export type GetSettingsSendParams = {
type?: EmailTypeModel;
guid?: string;
};
