/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type GetVersionAllParams = {
unique?: string;
skip?: number;
take?: number;
variant?: string;
segment?: string;
};
