/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { DirectionModel } from './directionModel.js';

export type GetVersionByIdAuditLogParams = {
orderDirection?: DirectionModel;
skip?: number;
take?: number;
};
