/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export interface GlobalWorkflowVariablesModel {
  historyCleanupEnabled: boolean;
  configureApprovalThreshold: boolean;
  defaultApprovalThreshold: number;
  mandatoryComments: boolean;
  adminCanEdit: boolean;
  allowAttachments: boolean;
  allowScheduling: boolean;
  extendPermissions: boolean;
  lockIfActive: boolean;
  requireUnpublish: boolean;
  flowType: number;
}
