/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ApprovalThresholdModel } from './approvalThresholdModel.js';
import type { FlowTypeModel } from './flowTypeModel.js';

export interface GlobalWorkflowVariablesModel {
  historyCleanupEnabled: boolean;
  configureApprovalThreshold: boolean;
  defaultApprovalThreshold: ApprovalThresholdModel;
  mandatoryComments: boolean;
  adminCanEdit: boolean;
  allowAttachments: boolean;
  allowScheduling: boolean;
  extendPermissions: boolean;
  lockIfActive: boolean;
  requireUnpublish: boolean;
  flowType: FlowTypeModel;
}
