/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { LanguageModel } from './languageModel.js';
import type { GlobalUserVariablesModel } from './globalUserVariablesModel.js';
import type { GlobalWorkflowVariablesModel } from './globalWorkflowVariablesModel.js';

export interface GlobalVariablesModel {
  culture: LanguageModel;
  user: GlobalUserVariablesModel;
  workflow: GlobalWorkflowVariablesModel;
  availableLanguages: LanguageModel[];
}
