/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { HistoryCleanupConfigModelStatusesToDelete } from './historyCleanupConfigModelStatusesToDelete.js';

export interface HistoryCleanupConfigModel {
  enableCleanup: boolean;
  /** @nullable */
  keepHistoryForDays?: number | null;
  statusesToDelete: HistoryCleanupConfigModelStatusesToDelete;
  isNodeConfig: boolean;
  editable: boolean;
  entityKey: string;
  /** @nullable */
  entityName?: string | null;
}
