/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export interface InitiateWorkflowRequestModel {
  entityId: string;
  /** @nullable */
  entityType?: string | null;
  comment: string;
  publish: boolean;
  variant: string[];
  /** @nullable */
  releaseDate?: string | null;
  /** @nullable */
  expireDate?: string | null;
  /** @nullable */
  attachmentId?: number | null;
  /** @nullable */
  userId?: string | null;
}
