/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { WorkflowStatusModel } from './workflowStatusModel.js';
import type { WorkflowTypeModel } from './workflowTypeModel.js';

export interface InstanceDetailModel {
  /** @nullable */
  completedOn?: string | null;
  requestedOn: string;
  /** @nullable */
  expireDate?: string | null;
  /** @nullable */
  releaseDate?: string | null;
  key: string;
  requestedByKey: string;
  /** @nullable */
  entityKey?: string | null;
  totalSteps: number;
  /** @nullable */
  requestedBy?: string | null;
  /** @nullable */
  variantCode?: string | null;
  /** @nullable */
  variantName?: string | null;
  /** @nullable */
  attachment?: string | null;
  /** @nullable */
  comment?: string | null;
  /** @nullable */
  segments?: string | null;
  /** @nullable */
  entityType?: string | null;
  scheduled: boolean;
  status: WorkflowStatusModel;
  type: WorkflowTypeModel;
}
