/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ApprovalGroupDetailPermissionConfigModel } from './approvalGroupDetailPermissionConfigModel.js';

export interface NodePermissionsResponseModel {
  node: ApprovalGroupDetailPermissionConfigModel[];
  contentType: ApprovalGroupDetailPermissionConfigModel[];
  inherited: ApprovalGroupDetailPermissionConfigModel[];
  new: ApprovalGroupDetailPermissionConfigModel[];
  excluded: boolean;
  /** @nullable */
  inheritedFrom?: string | null;
  locked: boolean;
}
