/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ReleaseSetCollectionResponseModel } from './releaseSetCollectionResponseModel.js';

export interface PagedReleaseSetCollectionResponseModel {
  currentPage: number;
  totalItems: number;
  itemsPerPage: number;
  items: ReleaseSetCollectionResponseModel[];
}
