/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ConfigTypeModel } from './configTypeModel.js';
import type { PropertyDisplayModelValue } from './propertyDisplayModelValue.js';

export interface PropertyDisplayModel {
  config: ConfigTypeModel[];
  readonly: boolean;
  hidden: boolean;
  requiresLicense: boolean;
  /** @nullable */
  value?: PropertyDisplayModelValue;
}
