/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { PropertyValueDtoModelValue } from './propertyValueDtoModelValue.js';

export interface PropertyValueDtoModel {
  /** @nullable */
  culture?: string | null;
  /** @nullable */
  segment?: string | null;
  /** @minLength 1 */
  alias: string;
  /** @nullable */
  value?: PropertyValueDtoModelValue;
}
