/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ReleaseSetTaskResponseModelAssignedTo } from './releaseSetTaskResponseModelAssignedTo.js';
import type { UserItemModel } from './userItemModel.js';
import type { ReleaseSetTaskStatusModel } from './releaseSetTaskStatusModel.js';

export interface ReleaseSetTaskResponseModel {
  unique: string;
  /** @nullable */
  parentUnique?: string | null;
  name: string;
  /** @nullable */
  icon?: string | null;
  readonly entityType: string;
  /** @nullable */
  createdOn?: string | null;
  /** @nullable */
  completedOn?: string | null;
  /** @nullable */
  assignedTo?: ReleaseSetTaskResponseModelAssignedTo;
  createdBy: UserItemModel;
  status: ReleaseSetTaskStatusModel;
  /** @nullable */
  description?: string | null;
}
