/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { VersionExpireActionModel } from './versionExpireActionModel.js';
import type { ReleaseSetItemStatusModel } from './releaseSetItemStatusModel.js';

export interface ReleaseSetVersionResponseModel {
  unique: string;
  /** @nullable */
  parentUnique?: string | null;
  name: string;
  /** @nullable */
  icon?: string | null;
  readonly entityType: string;
  /** @nullable */
  releaseDate?: string | null;
  /** @nullable */
  expireDate?: string | null;
  expireAction: VersionExpireActionModel;
  status: ReleaseSetItemStatusModel;
  /** @nullable */
  variant?: string | null;
  /** @nullable */
  segment?: string | null;
  nodeUnique: string;
}
