/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type ReleaseSetItemStatusModel = typeof ReleaseSetItemStatusModel[keyof typeof ReleaseSetItemStatusModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReleaseSetItemStatusModel = {
  Draft: 'Draft',
  ReadyToPublish: 'ReadyToPublish',
  Published: 'Published',
} as const;
