/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ReleaseSetStatusModel } from './releaseSetStatusModel.js';
import type { UserItemModel } from './userItemModel.js';
import type { ReleaseSetItemResponseModel } from './releaseSetItemResponseModel.js';
import type { ReleaseSetTaskResponseModel } from './releaseSetTaskResponseModel.js';

export interface ReleaseSetDetailResponseModel {
  unique: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  icon?: string | null;
  itemCount: number;
  status: ReleaseSetStatusModel;
  readonly entityType: string;
  /** @nullable */
  description?: string | null;
  owner: UserItemModel;
  /** @nullable */
  expireDate?: string | null;
  /** @nullable */
  releaseDate?: string | null;
  /** @nullable */
  createDate?: string | null;
  /** @nullable */
  updateDate?: string | null;
  collaborators: UserItemModel[];
  items: ReleaseSetItemResponseModel[];
  tasks: ReleaseSetTaskResponseModel[];
}
