/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ReleaseSetItemStatusModel } from './releaseSetItemStatusModel.js';
import type { ReleaseSetVersionResponseModel } from './releaseSetVersionResponseModel.js';

export interface ReleaseSetItemResponseModel {
  readonly entityType: string;
  name: string;
  unique: string;
  /** @nullable */
  icon?: string | null;
  status: ReleaseSetItemStatusModel;
  items: ReleaseSetVersionResponseModel[];
}
