/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ReleaseSetStatusModel } from './releaseSetStatusModel.js';

export interface ReleaseSetCollectionResponseModel {
  unique: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  icon?: string | null;
  itemCount: number;
  status: ReleaseSetStatusModel;
}
