/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type ReleaseSetStatusModel = typeof ReleaseSetStatusModel[keyof typeof ReleaseSetStatusModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReleaseSetStatusModel = {
  Draft: 'Draft',
  ReadyToPublish: 'ReadyToPublish',
  Published: 'Published',
  Complete: 'Complete',
} as const;
