/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type ReleaseSetTaskStatusModel = typeof ReleaseSetTaskStatusModel[keyof typeof ReleaseSetTaskStatusModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReleaseSetTaskStatusModel = {
  Active: 'Active',
  Complete: 'Complete',
  Closed: 'Closed',
} as const;
