/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ScheduledContentTypeModel } from './scheduledContentTypeModel.js';

export interface ScheduledContentLegendItemResponseModel {
  key: string;
  type: ScheduledContentTypeModel;
}
