/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ScheduledContentLegendItemResponseModel } from './scheduledContentLegendItemResponseModel.js';
import type { ScheduledContentResponseModel } from './scheduledContentResponseModel.js';

export interface ScheduledContentWithLegendResponseModel {
  legend: ScheduledContentLegendItemResponseModel[];
  items: ScheduledContentResponseModel[];
}
