/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ScheduledContentTypeModel } from './scheduledContentTypeModel.js';
import type { ReleaseSetStatusModel } from './releaseSetStatusModel.js';

export interface ScheduledContentResponseModel {
  unique: string;
  /** @nullable */
  nodeUnique?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  culture?: string | null;
  /** @nullable */
  fromDate?: string | null;
  /** @nullable */
  toDate?: string | null;
  /** @nullable */
  action?: string | null;
  /** @nullable */
  icon?: string | null;
  type: ScheduledContentTypeModel;
  status: ReleaseSetStatusModel;
  setStatus: ReleaseSetStatusModel;
}
