/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type ScheduledContentTypeModel = typeof ScheduledContentTypeModel[keyof typeof ScheduledContentTypeModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScheduledContentTypeModel = {
  Null: 'Null',
  Content: 'Content',
  ReleaseSet: 'ReleaseSet',
  ReleaseSetItem: 'ReleaseSetItem',
} as const;
