/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ConfigTypeModel } from './configTypeModel.js';
import type { SettingsPropertyDisplayModelValue } from './settingsPropertyDisplayModelValue.js';

export interface SettingsPropertyDisplayModel {
  config: ConfigTypeModel[];
  readonly: boolean;
  hidden: boolean;
  requiresLicense: boolean;
  /** @nullable */
  value?: SettingsPropertyDisplayModelValue;
  alias: string;
  label: string;
  editorUiAlias: string;
}
