/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type TaskStatusModel = typeof TaskStatusModel[keyof typeof TaskStatusModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskStatusModel = {
  Null: 'Null',
  Approved: 'Approved',
  Rejected: 'Rejected',
  PendingApproval: 'PendingApproval',
  NotRequired: 'NotRequired',
  Cancelled: 'Cancelled',
  Errored: 'Errored',
  Resubmitted: 'Resubmitted',
  CancelledByThirdParty: 'CancelledByThirdParty',
  Excluded: 'Excluded',
  AwaitingResubmission: 'AwaitingResubmission',
} as const;
