/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export interface User2ApprovalGroupModel {
  userUnique: string;
  groupUnique: string;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  inherited: boolean;
  isActive: boolean;
}
