/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type VersionExpireActionModel = typeof VersionExpireActionModel[keyof typeof VersionExpireActionModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VersionExpireActionModel = {
  Revert: 'Revert',
  Unpublish: 'Unpublish',
} as const;
