/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { WorkflowInstanceTableTaskResponseModel } from './workflowInstanceTableTaskResponseModel.js';
import type { WorkflowInstanceTableResponseModelDocument } from './workflowInstanceTableResponseModelDocument.js';

export interface WorkflowInstanceTableResponseModel {
  unique: string;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  culture?: string | null;
  /** @nullable */
  action?: string | null;
  /** @nullable */
  requestedBy?: string | null;
  /** @nullable */
  requestedOn?: string | null;
  /** @nullable */
  comment?: string | null;
  scheduled: boolean;
  tasks: WorkflowInstanceTableTaskResponseModel[];
  /** @nullable */
  document?: WorkflowInstanceTableResponseModelDocument;
}
