/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export interface WorkflowDiffContainerModel {
  alias: string;
  /** @nullable */
  label: string | null;
  /** @nullable */
  type: string | null;
}
