/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export interface WorkflowTaskCollectionItemModel {
  /** @nullable */
  actionedByName?: string | null;
  /** @nullable */
  actionedById?: string | null;
  actionedByAdmin: boolean;
  /** @nullable */
  actionedOn?: string | null;
  /** @nullable */
  comment?: string | null;
  /** @nullable */
  status?: number | null;
  linked: boolean;
  future: boolean;
}
