/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { NodePermissionsResponseModel } from './nodePermissionsResponseModel.js';

/**
 * @nullable
 */
export type WorkflowScaffoldResponseModelConfig = NodePermissionsResponseModel | null;
