/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { GlobalWorkflowVariablesModel } from './globalWorkflowVariablesModel.js';
import type { WorkflowInformationResponseModelLicense } from './workflowInformationResponseModelLicense.js';
import type { WorkflowInformationResponseModelVersion } from './workflowInformationResponseModelVersion.js';

export interface WorkflowInformationResponseModel {
  globalVariables: GlobalWorkflowVariablesModel;
  /** @nullable */
  license: WorkflowInformationResponseModelLicense;
  hubUrl: string;
  featureFlags: string[];
  /** @nullable */
  version: WorkflowInformationResponseModelVersion;
}
