/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { WorkflowTaskCollectionModel } from './workflowTaskCollectionModel.js';

export interface WorkflowTasksForInstanceResponseModel {
  taskCollection: WorkflowTaskCollectionModel[];
  totalSteps: number;
  currentStep: number;
}
