/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { WorkflowTaskModelInstance } from './workflowTaskModelInstance.js';
import type { WorkflowTaskModelNode } from './workflowTaskModelNode.js';
import type { WorkflowTaskModelUserGroup } from './workflowTaskModelUserGroup.js';
import type { WorkflowTaskModelGroup } from './workflowTaskModelGroup.js';

export interface WorkflowTaskModel {
  /** @nullable */
  actionedByAdmin?: boolean | null;
  /** @nullable */
  completedOn?: string | null;
  requestedOn: string;
  /** @nullable */
  actionedByUserId?: string | null;
  /** @nullable */
  assignTo?: string | null;
  approvedByIds: string[];
  /** @nullable */
  instance?: WorkflowTaskModelInstance;
  currentStep: number;
  id: number;
  typeId: number;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  node?: WorkflowTaskModelNode;
  /** @nullable */
  backofficeUrl?: string | null;
  /** @nullable */
  comment?: string | null;
  /** @nullable */
  completedBy?: string | null;
  /** @nullable */
  statusName?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  typeDescription?: string | null;
  /** @nullable */
  userGroup?: WorkflowTaskModelUserGroup;
  /** @nullable */
  group?: WorkflowTaskModelGroup;
}
