/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ApprovalGroupItemResponseModel } from './approvalGroupItemResponseModel.js';
import type { WorkflowTaskCollectionItemModel } from './workflowTaskCollectionItemModel.js';

export interface WorkflowTaskCollectionModel {
  group: ApprovalGroupItemResponseModel;
  items: WorkflowTaskCollectionItemModel[];
  /** @nullable */
  status?: number | null;
  actionedByAdmin: boolean;
  approvalCount: number;
  approvalsRequired: number;
  approvalStep: number;
  future: boolean;
}
