/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { WorkflowInstanceResponseModelNode } from './workflowInstanceResponseModelNode.js';
import type { WorkflowInstanceResponseModelInstance } from './workflowInstanceResponseModelInstance.js';
import type { WorkflowPermissionResponseModel } from './workflowPermissionResponseModel.js';
import type { WorkflowTaskResponseModel } from './workflowTaskResponseModel.js';

export interface WorkflowInstanceResponseModel {
  /** @nullable */
  node?: WorkflowInstanceResponseModelNode;
  /** @nullable */
  instance?: WorkflowInstanceResponseModelInstance;
  permissions: WorkflowPermissionResponseModel[];
  tasks: WorkflowTaskResponseModel[];
}
