/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type WorkflowTypeModel = typeof WorkflowTypeModel[keyof typeof WorkflowTypeModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkflowTypeModel = {
  Null: 'Null',
  Publish: 'Publish',
  Unpublish: 'Unpublish',
} as const;
