/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { CreateMemberTypeRequestModelCollection } from './createMemberTypeRequestModelCollection.js';
import type { CreateMemberTypePropertyTypeRequestModel } from './createMemberTypePropertyTypeRequestModel.js';
import type { CreateMemberTypePropertyTypeContainerRequestModel } from './createMemberTypePropertyTypeContainerRequestModel.js';
import type { MemberTypeCompositionModel } from './memberTypeCompositionModel.js';

export interface CreateMemberTypeRequestModel {
  /** @minLength 1 */
  alias: string;
  /** @minLength 1 */
  name: string;
  /** @nullable */
  description?: string | null;
  /** @minLength 1 */
  icon: string;
  allowedAsRoot: boolean;
  variesByCulture: boolean;
  variesBySegment: boolean;
  /** @nullable */
  collection?: CreateMemberTypeRequestModelCollection;
  isElement: boolean;
  properties: CreateMemberTypePropertyTypeRequestModel[];
  containers: CreateMemberTypePropertyTypeContainerRequestModel[];
  /** @nullable */
  id?: string | null;
  compositions: MemberTypeCompositionModel[];
}
