/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { CurrentUserResponseModelPermissionsItem } from './currentUserResponseModelPermissionsItem.js';

export interface CurrentUserResponseModel {
  email: string;
  userName: string;
  name: string;
  userGroupIds: ReferenceByIdModel[];
  id: string;
  /** @nullable */
  languageIsoCode: string | null;
  documentStartNodeIds: ReferenceByIdModel[];
  hasDocumentRootAccess: boolean;
  mediaStartNodeIds: ReferenceByIdModel[];
  hasMediaRootAccess: boolean;
  avatarUrls: string[];
  languages: string[];
  hasAccessToAllLanguages: boolean;
  hasAccessToSensitiveData: boolean;
  fallbackPermissions: string[];
  permissions: CurrentUserResponseModelPermissionsItem[];
  allowedSections: string[];
  isAdmin: boolean;
}
