/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export interface DatabaseInstallRequestModel {
  id: string;
  /** @minLength 1 */
  providerName: string;
  /** @nullable */
  server?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
  useIntegratedAuthentication: boolean;
  /** @nullable */
  connectionString?: string | null;
  trustServerCertificate: boolean;
}
