/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */

export type DirectionModel = typeof DirectionModel[keyof typeof DirectionModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DirectionModel = {
  Ascending: 'Ascending',
  Descending: 'Descending',
} as const;
