/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentReferenceResponseModelType } from './documentReferenceResponseModelType.js';
import type { TrackedReferenceDocumentTypeModel } from './trackedReferenceDocumentTypeModel.js';
import type { DocumentVariantItemResponseModel } from './documentVariantItemResponseModel.js';

export interface DocumentReferenceResponseModel {
  $type: DocumentReferenceResponseModelType;
  id: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  published?: boolean | null;
  documentType: TrackedReferenceDocumentTypeModel;
  variants: DocumentVariantItemResponseModel[];
}
