/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MediaValueResponseModelValue } from './mediaValueResponseModelValue.js';

export interface MediaValueResponseModel {
  /** @nullable */
  culture?: string | null;
  /** @nullable */
  segment?: string | null;
  /** @minLength 1 */
  alias: string;
  /** @nullable */
  value?: MediaValueResponseModelValue;
  /** @minLength 1 */
  editorAlias: string;
}
