/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MediaTypePropertyTypeReferenceResponseModelType } from './mediaTypePropertyTypeReferenceResponseModelType.js';
import type { TrackedReferenceMediaTypeModel } from './trackedReferenceMediaTypeModel.js';

export interface MediaTypePropertyTypeReferenceResponseModel {
  $type: MediaTypePropertyTypeReferenceResponseModelType;
  id: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  alias?: string | null;
  mediaType: TrackedReferenceMediaTypeModel;
}
