/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MediaTypeTreeItemResponseModelParent } from './mediaTypeTreeItemResponseModelParent.js';

export interface MediaTypeTreeItemResponseModel {
  hasChildren: boolean;
  id: string;
  /** @nullable */
  parent?: MediaTypeTreeItemResponseModelParent;
  name: string;
  isFolder: boolean;
  icon: string;
  isDeletable: boolean;
}
