/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MemberTypePropertyTypeReferenceResponseModelType } from './memberTypePropertyTypeReferenceResponseModelType.js';
import type { TrackedReferenceMemberTypeModel } from './trackedReferenceMemberTypeModel.js';

export interface MemberTypePropertyTypeReferenceResponseModel {
  $type: MemberTypePropertyTypeReferenceResponseModelType;
  id: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  alias?: string | null;
  memberType: TrackedReferenceMemberTypeModel;
}
