/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DefaultReferenceResponseModel } from './defaultReferenceResponseModel.js';
import type { DocumentReferenceResponseModel } from './documentReferenceResponseModel.js';
import type { DocumentTypePropertyTypeReferenceResponseModel } from './documentTypePropertyTypeReferenceResponseModel.js';
import type { MediaReferenceResponseModel } from './mediaReferenceResponseModel.js';
import type { MediaTypePropertyTypeReferenceResponseModel } from './mediaTypePropertyTypeReferenceResponseModel.js';
import type { MemberReferenceResponseModel } from './memberReferenceResponseModel.js';
import type { MemberTypePropertyTypeReferenceResponseModel } from './memberTypePropertyTypeReferenceResponseModel.js';

export type PagedIReferenceResponseModelItemsItem = DefaultReferenceResponseModel | DocumentReferenceResponseModel | DocumentTypePropertyTypeReferenceResponseModel | MediaReferenceResponseModel | MediaTypePropertyTypeReferenceResponseModel | MemberReferenceResponseModel | MemberTypePropertyTypeReferenceResponseModel;
