/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { ReferenceByIdModel } from './referenceByIdModel.js';
import type { MemberItemResponseModel } from './memberItemResponseModel.js';
import type { MemberGroupItemResponseModel } from './memberGroupItemResponseModel.js';

export interface PublicAccessResponseModel {
  loginDocument: ReferenceByIdModel;
  errorDocument: ReferenceByIdModel;
  members: MemberItemResponseModel[];
  groups: MemberGroupItemResponseModel[];
}
