/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { TemplateQueryExecuteModelRootDocument } from './templateQueryExecuteModelRootDocument.js';
import type { TemplateQueryExecuteFilterPresentationModel } from './templateQueryExecuteFilterPresentationModel.js';
import type { TemplateQueryExecuteModelSort } from './templateQueryExecuteModelSort.js';

export interface TemplateQueryExecuteModel {
  /** @nullable */
  rootDocument?: TemplateQueryExecuteModelRootDocument;
  /** @nullable */
  documentTypeAlias?: string | null;
  /** @nullable */
  filters?: TemplateQueryExecuteFilterPresentationModel[] | null;
  /** @nullable */
  sort?: TemplateQueryExecuteModelSort;
  take: number;
}
