/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { DocumentValueModel } from './documentValueModel.js';
import type { DocumentVariantRequestModel } from './documentVariantRequestModel.js';
import type { UpdateDocumentRequestModelTemplate } from './updateDocumentRequestModelTemplate.js';

export interface UpdateDocumentRequestModel {
  values: DocumentValueModel[];
  variants: DocumentVariantRequestModel[];
  /** @nullable */
  template?: UpdateDocumentRequestModelTemplate;
}
