/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { UserGroupResponseModelDocumentStartNode } from './userGroupResponseModelDocumentStartNode.js';
import type { UserGroupResponseModelMediaStartNode } from './userGroupResponseModelMediaStartNode.js';
import type { UserGroupResponseModelPermissionsItem } from './userGroupResponseModelPermissionsItem.js';

export interface UserGroupResponseModel {
  name: string;
  alias: string;
  /** @nullable */
  icon?: string | null;
  sections: string[];
  languages: string[];
  hasAccessToAllLanguages: boolean;
  /** @nullable */
  documentStartNode?: UserGroupResponseModelDocumentStartNode;
  documentRootAccess: boolean;
  /** @nullable */
  mediaStartNode?: UserGroupResponseModelMediaStartNode;
  mediaRootAccess: boolean;
  fallbackPermissions: string[];
  permissions: UserGroupResponseModelPermissionsItem[];
  id: string;
  isDeletable: boolean;
  aliasCanBeChanged: boolean;
}
