/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ApiMediaWithCropsResponseModelProperties } from './apiMediaWithCropsResponseModelProperties.js';
import type { ApiMediaWithCropsResponseModelFocalPoint } from './apiMediaWithCropsResponseModelFocalPoint.js';
import type { ImageCropModel } from './imageCropModel.js';

export interface ApiMediaWithCropsResponseModel {
  readonly id: string;
  readonly name: string;
  readonly mediaType: string;
  readonly url: string;
  /** @nullable */
  readonly extension?: string | null;
  /** @nullable */
  readonly width?: number | null;
  /** @nullable */
  readonly height?: number | null;
  /** @nullable */
  readonly bytes?: number | null;
  readonly properties: ApiMediaWithCropsResponseModelProperties;
  /** @nullable */
  focalPoint?: ApiMediaWithCropsResponseModelFocalPoint;
  /** @nullable */
  crops?: ImageCropModel[] | null;
  path: string;
  createDate: string;
  updateDate: string;
}
