/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ImageCropModelCoordinates } from './imageCropModelCoordinates.js';

export interface ImageCropModel {
  /** @nullable */
  alias?: string | null;
  width: number;
  height: number;
  /** @nullable */
  coordinates?: ImageCropModelCoordinates;
}
