/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { LogLevelModel } from './logLevelModel.js';
import type { LogMessagePropertyPresentationModel } from './logMessagePropertyPresentationModel.js';

export interface LogMessageResponseModel {
  timestamp: string;
  level: LogLevelModel;
  /** @nullable */
  messageTemplate?: string | null;
  /** @nullable */
  renderedMessage?: string | null;
  properties: LogMessagePropertyPresentationModel[];
  /** @nullable */
  exception?: string | null;
}
