/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { MediaTreeItemResponseModelParent } from './mediaTreeItemResponseModelParent.js';
import type { MediaTypeReferenceResponseModel } from './mediaTypeReferenceResponseModel.js';
import type { VariantItemResponseModel } from './variantItemResponseModel.js';

export interface MediaTreeItemResponseModel {
  hasChildren: boolean;
  /** @nullable */
  parent?: MediaTreeItemResponseModelParent;
  noAccess: boolean;
  isTrashed: boolean;
  id: string;
  createDate: string;
  mediaType: MediaTypeReferenceResponseModel;
  variants: VariantItemResponseModel[];
}
