/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Management API
 * This shows all APIs available in this version of Umbraco - including all the legacy apis that are available for backward compatibility
 * OpenAPI spec version: Latest
 */
import type { UpdateMediaTypeRequestModelCollection } from './updateMediaTypeRequestModelCollection.js';
import type { UpdateMediaTypePropertyTypeRequestModel } from './updateMediaTypePropertyTypeRequestModel.js';
import type { UpdateMediaTypePropertyTypeContainerRequestModel } from './updateMediaTypePropertyTypeContainerRequestModel.js';
import type { MediaTypeSortModel } from './mediaTypeSortModel.js';
import type { MediaTypeCompositionModel } from './mediaTypeCompositionModel.js';

export interface UpdateMediaTypeRequestModel {
  /** @minLength 1 */
  alias: string;
  /** @minLength 1 */
  name: string;
  /** @nullable */
  description?: string | null;
  /** @minLength 1 */
  icon: string;
  allowedAsRoot: boolean;
  variesByCulture: boolean;
  variesBySegment: boolean;
  /** @nullable */
  collection?: UpdateMediaTypeRequestModelCollection;
  isElement: boolean;
  properties: UpdateMediaTypePropertyTypeRequestModel[];
  containers: UpdateMediaTypePropertyTypeContainerRequestModel[];
  allowedMediaTypes: MediaTypeSortModel[];
  compositions: MediaTypeCompositionModel[];
}
