/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { WorkflowStatusModel } from './workflowStatusModel.js';
import type { WorkflowTaskModel } from './workflowTaskModel.js';

export interface ActionWorkflowResponseModel {
  workflowStatus: WorkflowStatusModel[];
  activeWorkflows: WorkflowTaskModel[];
}
