/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type AdvancedSearchTypeModel = typeof AdvancedSearchTypeModel[keyof typeof AdvancedSearchTypeModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdvancedSearchTypeModel = {
  Null: 'Null',
  All: 'All',
  Some: 'Some',
  Single: 'Single',
  Datatype: 'Datatype',
  PropertyEditor: 'PropertyEditor',
} as const;
