/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ApprovalGroupDetailPermissionResponseModel } from './approvalGroupDetailPermissionResponseModel.js';
import type { ApprovalGroupCollectionMemberResponseModel } from './approvalGroupCollectionMemberResponseModel.js';

export interface ApprovalGroupCollectionReponseModel {
  name: string;
  unique: string;
  /** @nullable */
  icon?: string | null;
  /** @nullable */
  groupEmail?: string | null;
  permissions: ApprovalGroupDetailPermissionResponseModel[];
  members: ApprovalGroupCollectionMemberResponseModel[];
}
