/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ChartDataPointModel } from './chartDataPointModel.js';

export interface ChartSeriesModel {
  label: string;
  key: string;
  borderColor: string;
  backgroundColor: string;
  type: string;
  data: ChartDataPointModel[];
}
