/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ApprovalGroupItemResponseModel } from './approvalGroupItemResponseModel.js';
import type { ContentReviewsDetailedConfigModelReviewedBy } from './contentReviewsDetailedConfigModelReviewedBy.js';

export interface ContentReviewsDetailedConfigModel {
  id: number;
  /** @nullable */
  documentKey?: string | null;
  name: string;
  /** @nullable */
  documentTypeKey?: string | null;
  excluded: boolean;
  expired: boolean;
  period: number;
  variant: string;
  variantName: string;
  /** @nullable */
  groups?: ApprovalGroupItemResponseModel[] | null;
  groupIds: string;
  /** @nullable */
  dueOn?: string | null;
  /** @nullable */
  reviewedOn?: string | null;
  /** @nullable */
  reviewedBy?: ContentReviewsDetailedConfigModelReviewedBy;
  /** @nullable */
  inheritedFrom?: string | null;
  /** @nullable */
  inheritedType?: string | null;
  /** @nullable */
  icon?: string | null;
  isDefaultVariant: boolean;
  /** @nullable */
  externalReviewers?: string | null;
}
