/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { DocumentItemResponseModel } from './documentItemResponseModel.js';

export interface ContentReviewRequestModel {
  document: DocumentItemResponseModel;
  dueOn: string;
}
