/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { SettingsPropertyDisplayModel } from './settingsPropertyDisplayModel.js';
import type { PropertyDisplayModel } from './propertyDisplayModel.js';

export interface ContentReviewsSettingsModel {
  properties: SettingsPropertyDisplayModel[];
  contentItemReviews: PropertyDisplayModel;
  documentTypeReviews: PropertyDisplayModel;
  relativeTo: number;
  force: boolean;
}
