/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { ApprovalGroupItemResponseModel } from './approvalGroupItemResponseModel.js';

export interface DocumentTypePermissionConfigModel {
  /** @nullable */
  contentTypeUnique?: string | null;
  permission: number;
  /** @nullable */
  condition?: string | null;
  culture: string;
  /** @nullable */
  approvalThreshold?: number | null;
  group: ApprovalGroupItemResponseModel;
}
