/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type EventMessageTypeModel = typeof EventMessageTypeModel[keyof typeof EventMessageTypeModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventMessageTypeModel = {
  Default: 'Default',
  Info: 'Info',
  Error: 'Error',
  Success: 'Success',
  Warning: 'Warning',
} as const;
