/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export interface NodeSlimModel {
  key: string;
  contentTypeKey: string;
  /** @nullable */
  name?: string | null;
  url: string;
  exists: boolean;
  new: boolean;
  icon: string;
}
