/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { PropertyDetailModelConfig } from './propertyDetailModelConfig.js';
import type { PropertyDetailModelValue } from './propertyDetailModelValue.js';

export interface PropertyDetailModel {
  name: string;
  key: string;
  selected: boolean;
  dataTypeKey: string;
  /** @nullable */
  propertyEditorAlias?: string | null;
  /** @nullable */
  propertyEditorUiAlias?: string | null;
  alias: string;
  /** @nullable */
  config?: PropertyDetailModelConfig;
  /** @nullable */
  value?: PropertyDetailModelValue;
  icon: string;
}
