/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { PropertyDetailModel } from './propertyDetailModel.js';

export interface SelectableContentTypePropertyDetailModel {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  alias?: string | null;
  id: number;
  key: string;
  varies: boolean;
  icon: string;
  properties: PropertyDetailModel[];
  selected: boolean;
}
