/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { GlobalVariablesModel } from './globalVariablesModel.js';
import type { WorkflowInformationResponseModelLicense } from './workflowInformationResponseModelLicense.js';

export interface WorkflowInformationResponseModel {
  globalVariables: GlobalVariablesModel;
  /** @nullable */
  license: WorkflowInformationResponseModelLicense;
  hubUrl: string;
}
