/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { WorkflowContentDiffModelLanguage } from './workflowContentDiffModelLanguage.js';
import type { WorkflowDiffPropertyModel } from './workflowDiffPropertyModel.js';

export interface WorkflowContentDiffModel {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  language?: WorkflowContentDiffModelLanguage;
  properties: WorkflowDiffPropertyModel[];
}
