/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { WorkflowDiffContainerModel } from './workflowDiffContainerModel.js';

/**
 * @nullable
 */
export type WorkflowDiffPropertyModelContainer = WorkflowDiffContainerModel | null;
