/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { WorkflowDiffPropertyModelValue } from './workflowDiffPropertyModelValue.js';
import type { WorkflowDiffPropertyModelContainer } from './workflowDiffPropertyModelContainer.js';

export interface WorkflowDiffPropertyModel {
  /** @nullable */
  label?: string | null;
  /** @nullable */
  alias?: string | null;
  /** @nullable */
  value?: WorkflowDiffPropertyModelValue;
  /** @nullable */
  container?: WorkflowDiffPropertyModelContainer;
}
