/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */

export type WorkflowActionModel = typeof WorkflowActionModel[keyof typeof WorkflowActionModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkflowActionModel = {
  Any: 'Any',
  Approve: 'Approve',
  Reject: 'Reject',
  Cancel: 'Cancel',
  Initiate: 'Initiate',
  Resubmit: 'Resubmit',
  Complete: 'Complete',
  Error: 'Error',
} as const;
