/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { WorkflowScaffoldResponseModelConfig } from './workflowScaffoldResponseModelConfig.js';
import type { WorkflowScaffoldResponseModelReview } from './workflowScaffoldResponseModelReview.js';
import type { WorkflowScaffoldResponseModelTasks } from './workflowScaffoldResponseModelTasks.js';

export interface WorkflowScaffoldResponseModel {
  /** @nullable */
  config?: WorkflowScaffoldResponseModelConfig;
  /** @nullable */
  review?: WorkflowScaffoldResponseModelReview;
  /** @nullable */
  tasks?: WorkflowScaffoldResponseModelTasks;
  activeVariants: string[];
}
