/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Workflow Management API
 * Describes the Umbraco Workflow Management API.
 * OpenAPI spec version: Latest
 */
import type { WorkflowSearchFilterModel } from './workflowSearchFilterModel.js';

export interface WorkflowSearchRequestModel {
  /** @nullable */
  skip?: number | null;
  take: number;
  /**
   * @nullable
   * @pattern ^([\w\d-_]){2,6}$
   */
  variant?: string | null;
  sortBy: string;
  sortDirection: string;
  filters: WorkflowSearchFilterModel;
}
